version: '2'
networks:
    bridge:

services:
  ca0:
    image: hyperledger/fabric-ca
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    ports: 
      - 7054:7054
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/peerOrg1-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/bc1d11c56de22a982dd1fe9bfab8e0ee37bd38a0eadd13174ba6c8605c92e421_sk -b admin:adminpw' -d
    volumes: 
      - /home/swangbj/gopath/src/github.com/hyperledger/fabric/common/tools/cryptogen/crypto-config/peerOrganizations/peerOrg1/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1
    networks: 
      - bridge

  ca1:
    image: hyperledger/fabric-ca
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    ports: 
      - 7055:7054
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/peerOrg2-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/37ad835f9033c99a5063d81eb4fb62672d635cb89b84918bd8badfc4746c2b34_sk -b admin:adminpw' -d
    volumes: 
      - /home/swangbj/gopath/src/github.com/hyperledger/fabric/common/tools/cryptogen/crypto-config/peerOrganizations/peerOrg2/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2
    networks: 
      - bridge

  zookeeper:
    image: hyperledger/fabric-zookeeper
    container_name: zookeeper
    networks: 
      - bridge

  kafka0:
    image: hyperledger/fabric-kafka
    environment: 
      - KAFKA_BROKER_ID=0
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
    depends_on: 
      - zookeeper
    container_name: kafka0
    ports: 
      - 9092:9092
    networks: 
      - bridge

  orderer0:
    image: hyperledger/fabric-orderer
    environment: 
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/opt/hyperledger/fabric/msp/crypto-config/ordererOrganizations/orderer.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererOrg1
      - ORDERER_GENERAL_LOCALMSPDIR=/opt/hyperledger/fabric/msp/crypto-config/ordererOrganizations/ordererOrg1/orderers/ordererOrg1Orderer1
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes: 
      - /home/swangbj/gopath/src/github.com/hyperledger/fabric/common/tools/cryptogen/crypto-config:/opt/hyperledger/fabric/msp/crypto-config
    ports: 
      - 5005:7050
    container_name: orderer0
    depends_on: 
      - zookeeper
      - kafka0
    networks: 
      - bridge

  peer0:
    image: hyperledger/fabric-peer
    environment: 
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_NEXT=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_GOSSIP_IGNORESECURITY=true
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_ID=peer0
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer0:5005
      - CORE_PEER_MSPCONFIGPATH=/opt/hyperledger/fabric/msp/crypto-config/peerOrganizations/peerOrg1/peers/peerOrg1Peer1
      - CORE_PEER_LOCALMSPID=PeerOrg1
    volumes: 
      - /var/run/:/host/var/run/
      - /home/swangbj/gopath/src/github.com/hyperledger/fabric/common/tools/cryptogen/crypto-config:/opt/hyperledger/fabric/msp/crypto-config
    ports: 
      - 7061:7051
      - 6051:7053
    depends_on: 
      - orderer0
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-defaultchain=false
    container_name: peer0
    networks: 
      - bridge

  peer1:
    image: hyperledger/fabric-peer
    environment: 
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_NEXT=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_GOSSIP_IGNORESECURITY=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_ID=peer1
      - CORE_PEER_GOSSIP_BOOTSTRAP=0.0.0.0:7061
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer0:5005
      - CORE_PEER_MSPCONFIGPATH=/opt/hyperledger/fabric/msp/crypto-config/peerOrganizations/peerOrg1/peers/peerOrg1Peer2
      - CORE_PEER_LOCALMSPID=PeerOrg1
    volumes: 
      - /var/run/:/host/var/run/
      - /home/swangbj/gopath/src/github.com/hyperledger/fabric/common/tools/cryptogen/crypto-config:/opt/hyperledger/fabric/msp/crypto-config
    ports: 
      - 7062:7051
      - 6052:7053
    depends_on: 
      - orderer0
      - peer0
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-defaultchain=false
    container_name: peer1
    networks: 
      - bridge

  peer2:
    image: hyperledger/fabric-peer
    environment: 
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_NEXT=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_GOSSIP_IGNORESECURITY=true
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_ID=peer2
      - CORE_PEER_GOSSIP_BOOTSTRAP=0.0.0.0:7061
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer0:5005
      - CORE_PEER_MSPCONFIGPATH=/opt/hyperledger/fabric/msp/crypto-config/peerOrganizations/peerOrg2/peers/peerOrg2Peer1
      - CORE_PEER_LOCALMSPID=PeerOrg2
    volumes: 
      - /var/run/:/host/var/run/
      - /home/swangbj/gopath/src/github.com/hyperledger/fabric/common/tools/cryptogen/crypto-config:/opt/hyperledger/fabric/msp/crypto-config
    ports: 
      - 7063:7051
      - 6053:7053
    depends_on: 
      - orderer0
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-defaultchain=false
    container_name: peer2
    networks: 
      - bridge

  peer3:
    image: hyperledger/fabric-peer
    environment: 
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_NEXT=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_GOSSIP_IGNORESECURITY=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_ID=peer3
      - CORE_PEER_GOSSIP_BOOTSTRAP=0.0.0.0:7061
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer0:5005
      - CORE_PEER_MSPCONFIGPATH=/opt/hyperledger/fabric/msp/crypto-config/peerOrganizations/peerOrg2/peers/peerOrg2Peer2
      - CORE_PEER_LOCALMSPID=PeerOrg2
    volumes: 
      - /var/run/:/host/var/run/
      - /home/swangbj/gopath/src/github.com/hyperledger/fabric/common/tools/cryptogen/crypto-config:/opt/hyperledger/fabric/msp/crypto-config
    ports: 
      - 7064:7051
      - 6054:7053
    depends_on: 
      - orderer0
      - peer2
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-defaultchain=false
    container_name: peer3
    networks: 
      - bridge

